name: gobox
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.0.0  
  http: ^1.2.0
  latlong2: ^0.9.1
  cupertino_icons: ^1.0.8
  postgres: ^3.5.9
  shared_preferences: ^2.2.3
  image_picker: ^0.8.7+5
  url_launcher: ^6.1.7
  flutter_dotenv: ^6.0.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  intl: ^0.19.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^19.5.0
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.2.0
  flutter_launcher_icons: ^0.14.4 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
   android: "icon_gobox"
   image_path: "asset/logo.png"
flutter:
  uses-material-design: true

  assets:
    - asset/